(define (problem asignar-reservas-ext2)
  (:domain reservas)
  (:objects
    D1 D2 D3 D4 D5 D6 D7 D8 D9 D10 D11 D12 D13 D14 D15 D16 D17 D18 D19 D20 D21 D22 D23 D24 D25 D26 D27 D28 D29 D30 - dia
    H1 H2 H3 H4 H5 H6 H7 - habitacion
    R1 R2 R3 R4 R5 R6 R7 R8 R9 - reserva
    N S E O - orientacion
  )
  (:init
    (= (que-dia D1) 1)
    (= (que-dia D2) 2)
    (= (que-dia D3) 3)
    (= (que-dia D4) 4)
    (= (que-dia D5) 5)
    (= (que-dia D6) 6)
    (= (que-dia D7) 7)
    (= (que-dia D8) 8)
    (= (que-dia D9) 9)
    (= (que-dia D10) 10)
    (= (que-dia D11) 11)
    (= (que-dia D12) 12)
    (= (que-dia D13) 13)
    (= (que-dia D14) 14)
    (= (que-dia D15) 15)
    (= (que-dia D16) 16)
    (= (que-dia D17) 17)
    (= (que-dia D18) 18)
    (= (que-dia D19) 19)
    (= (que-dia D20) 20)
    (= (que-dia D21) 21)
    (= (que-dia D22) 22)
    (= (que-dia D23) 23)
    (= (que-dia D24) 24)
    (= (que-dia D25) 25)
    (= (que-dia D26) 26)
    (= (que-dia D27) 27)
    (= (que-dia D28) 28)
    (= (que-dia D29) 29)
    (= (que-dia D30) 30)

    (= ( num-personas-hab H1) 3)
    (orientacion-hab H1 O)
    (= ( num-personas-hab H2) 3)
    (orientacion-hab H2 E)
    (= ( num-personas-hab H3) 1)
    (orientacion-hab H3 S)
    (= ( num-personas-hab H4) 2)
    (orientacion-hab H4 N)
    (= ( num-personas-hab H5) 4)
    (orientacion-hab H5 N)
    (= ( num-personas-hab H6) 2)
    (orientacion-hab H6 N)
    (= ( num-personas-hab H7) 3)
    (orientacion-hab H7 S)
    (= ( num-personas-res R1) 4)
    (= ( num-personas-res R2) 2)
    (= ( num-personas-res R3) 4)
    (= ( num-personas-res R4) 4)
    (= ( num-personas-res R5) 2)
    (= ( num-personas-res R6) 1)
    (= ( num-personas-res R7) 1)
    (= ( num-personas-res R8) 4)
    (= ( num-personas-res R9) 3)
    (= ( dia-inicial R1) 1)
    (= ( dia-final R1) 4)
    (= ( dia-inicial R2) 14)
    (= ( dia-final R2) 26)
    (= ( dia-inicial R3) 12)
    (= ( dia-final R3) 12)
    (= ( dia-inicial R4) 26)
    (= ( dia-final R4) 29)
    (= ( dia-inicial R5) 1)
    (= ( dia-final R5) 25)
    (= ( dia-inicial R6) 27)
    (= ( dia-final R6) 27)
    (= ( dia-inicial R7) 26)
    (= ( dia-final R7) 29)
    (= ( dia-inicial R8) 27)
    (= ( dia-final R8) 29)
    (= ( dia-inicial R9) 21)
    (= ( dia-final R9) 27)
    (orientacion-res R1 O)
    (orientacion-res R2 N)
    (orientacion-res R3 N)
    (orientacion-res R4 N)
    (orientacion-res R5 O)
    (orientacion-res R6 S)
    (orientacion-res R7 S)
    (orientacion-res R8 O)
    (orientacion-res R9 O)

    (= (reservas-no-asig) 0)
    (= (plazas-no-asig) 0)
    (= (reservas-orientacion-incorrecta) 0)
  )
  (:goal
    (forall
      (?r - reserva) 
      (or
        (reserva-asignada ?r)
        (reserva-no-asignada ?r)
      )
    )
  )
  (:metric minimize (+ (* 1 (reservas-orientacion-incorrecta)) (* 5 (reservas-no-asig))))
)